language: cpp

compiler:
    - gcc
    - clang

# We cannot use the default gcc, because it's too old and lacks C++11 support.

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - g++-4.8

# We have to install cmake manually, because Travis uses version 2.8, which does not work with Vc.

before_install:
    - wget https://cmake.org/files/v3.3/cmake-3.3.2-Linux-x86_64.tar.gz --no-check-certificate
    - tar xf cmake-3.3.2-Linux-x86_64.tar.gz

install:
    - export CMAKE=$(readlink -f "cmake-3.3.2-Linux-x86_64/bin/cmake")
    - export CTEST=$(readlink -f "cmake-3.3.2-Linux-x86_64/bin/ctest")
    - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi

before_script:
    - $CMAKE --version
    - mkdir build
    - cd build
    - $CMAKE ..

script:
    - $CXX --version
    - make -j2
    - $CTEST -j2
